name: Build, Upload to IAS and share on slack.

# Step 1: Choose the branch or branches you want to run this workflow
# Whenever A Code Pushed into master Branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Building release app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
          with:
            # Specify branch from where you are sharing build
            ref: [master , release/*]
      - name: Setting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running build command
        # Run your own gradle command to generate build.
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab

  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle

      - name: Uplaoding to IAS
          id: ias
          uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
          with:
            # Your service account JSON GitHub secret
            serviceAccountJsonPlainText: ${{ secrets.servicesecret }}
            # Your package name
            packageName: com.iniyan.githubactionexample
            aabFilePath: 'app-release.aab'

      - name: Uploading to test track
          uses: r0adkll/upload-google-play@v1
          with:
            # Your service account JSON GitHub secret
            serviceAccountJsonPlainText: ${{ secrets.servicesecret }}
            # Your package name
            packageName: com.iniyan.githubactionexample
            releaseFiles: app-release.aab
            track: internal

      - name: Sharing on slack
          uses: rtCamp/action-slack-notify@v2.1.0
          env:
            # Your slack webhook GitHub secret
            SLACK_WEBHOOK: ${{ secrets.slack }}
            # Slack channel where you want to notify
            SLACK_CHANNEL: rtBot
            SLACK_USERNAME: "JARVIS"
            SLACK_TITLE: "Internal testing build"
            SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}
